Functionality
FilipRegenczuk/COVID_status pull request #1
Opened 2020-12-28 12:05 UTC by FilipRegenczuk

2020-12-28 13:27 UTC, plks requested changes
Good job!

I can take a look at the data in a way I expected. I tried to discern a way you try to resolve a task like this. Right now, I'm able to give you some hints to write better software. Few points I'm missing in this pull request:

- installation. Your solution requires external dependency: `requests`. What if I try to run your program on a fresh OS? The point is: I'm missing a note "how to install" in a README file. Ideally, we can use [requirements file](https://pip.pypa.io/en/stable/user_guide/#requirements-files). Do you understand an issue it resolves?

- static analysis. Each programming language defines some general "guidelines" for code formatting. Python for example [PEP8 style guide](https://www.python.org/dev/peps/pep-0008/). As you can see it's quite long although there dozens of external tools like `flake`, `black` etc. Have you ever worked with static analysis tools?

- testing. Every professional need to test your software. We're going to heavily take a look at testing during our cooperation. Have you ever tested your software? Do you know why it's important?

2020-12-28 13:27 UTC, plks commented on covid_raport.py
> +sick = sick_percent(input_data['confirmed'], input_data['recovered'], input_data['deaths'], input_data['population'])
take a look at `sick_percent(**input_data)`. [args and kwargs magic](https://www.geeksforgeeks.org/args-kwargs-python/)

2020-12-28 13:27 UTC, plks commented on covid_raport.py
> +output_data = {
I understand your `input_data` and `output_data` I guess.

input means: `initial data` for my algorithm but `output` data is known as a post computed API response, right?

2020-12-28 18:18 UTC, FilipRegenczuk commented on covid_raport.py
> +import json
- installation: thanks for suggestion, I forgot about istallation in readme file. I understand this issue.
- static analysis: unfortunately I haven't worked with such tools before. Thanks for guide, I will review it :)
- testing: Unfortunately, on my studies there was not much about testing, and in the applications that I created I did not need to do more decent tests. Although I know they are important.

first comment: yes, I added some code before I created new branch, sorry. I will keep it in mind. Thanks for a tip.
second comment: fixed :)

2020-12-28 18:21 UTC, FilipRegenczuk commented on covid_raport.py
> +PATH = r"https://covid-api.mmediagroup.fr/v1/cases"
aah,  I forgot that in URL we use /, not backslashes, and raw string is useless.

2020-12-28 18:24 UTC, FilipRegenczuk commented on covid_raport.py
> +    exit(0)
Very useful suggestion. I used argparse module first time, because I haven't used named arguments before and I didn't know that we can use it without using sys module. Thanks

2020-12-28 18:26 UTC, FilipRegenczuk commented on covid_raport.py
> +    input_data = {
Yes true,  it is output_data of API response. This name can be confusing. I will reaplace it.

2020-12-28 18:27 UTC, FilipRegenczuk commented on covid_raport.py
> +output_data = {
Right, that's exactly what I meant

2020-12-28 18:30 UTC, FilipRegenczuk commented on covid_raport.py
> +# Function returning % of a country population that recovered
Thanks, i'm used to adding more than fewer comments, but indeed they are sometimes unnecessary. Moreover, sometimes they are actually pointless.

2020-12-29 06:54 UTC, FilipRegenczuk commented on covid_raport.py
> +sick = sick_percent(input_data['confirmed'], input_data['recovered'], input_data['deaths'], input_data['population'])
Damn, I saw a few times this args and kwargs but i did not expect something so comfortable. Thank you very much.

2020-12-31 12:06 UTC, plks commented on covid_raport.py
> +import json
will you fix installation and static analysis in this PR? I'm curious how you're going to approach these issues.

2020-12-31 12:10 UTC, plks commented on covid_raport.py
> +import json
Please catch up a bit on testing software. It's absolutely crucial for every project. We're going to work with tests very often. I'm sure that in a future PRs we're going to talk move often about tests than source code :D

2020-12-31 12:15 UTC, plks commented on covid_raport.py
> +# Function returning % of a country population that recovered
(ps you can remove all other comments?)

```
# Parser for command-line options
parser = argparse.ArgumentParser()
```
it's pointless as well. `argparse` is a parser. Does comment give you more info? (if you don't know argparse, google it)

```
# GET command
response = requests.get(PATH, params=country)
```
`requests.get` as a `# GET command` what a surprise!

```
# Function encoding to json and printing
def jprint(obj):
    text = json.dumps(obj, sort_keys=True, indent=4)
    print(text)
```

:)

2020-12-31 12:18 UTC, plks commented on covid_raport.py
> +output_data = {
I would even go with:
```
json_print({
    "recovered": recovered,
    "sick": sick
})
```

is `print_data` really necessary?

2020-12-31 12:22 UTC, plks reviewed
- what would happen if an external API won't respond with HTTP 200? Can we check it before moving on? We could print out "Oh no, unfortunately, some external error occurred. Please try again later". What do you think?

- what about caching external API response?

- have you ever seen `if __name__ == __main__` construct? Do you know what's for? Take a look at: [link](https://www.freecodecamp.org/news/if-name-main-python-example/), [link](https://stackoverflow.com/questions/419163/what-does-if-name-main-do)

2021-01-03 16:31 UTC, FilipRegenczuk commented on covid_raport.py
> +import json
Ok, I refilled readme file with installation section. I suggested there to ways to install required packages:
- by simple installation requests package
- and by installation requirements.txt

I am not sure that the second way is 100% right done, because despite the fact that I created virtual env, there is still a lot of packages.

2021-01-03 16:35 UTC, FilipRegenczuk commented on covid_raport.py
> +# Function returning % of a country population that recovered
True, I'm too used to commenting. Corrected.

2021-01-03 16:36 UTC, FilipRegenczuk commented on covid_raport.py
> +output_data = {
Is totally not necessary, because is used only once. Thanks, corrected.

2021-01-03 17:22 UTC, FilipRegenczuk commented
- Good observation with API status codes. I added simple if validation and stdout information.
- I am not sure that I understand correctly. Is it about the rest of status codes and dealing with them?
- I saw this construct a few times but I have never dived into this subject yet. Thank you very much for very informative links. Do you think that jprint() function in this construct is enough?

2021-01-29 12:15 UTC, closed without merging